#!/bin/bash
# ============================================================
# BP Agro — Pi 3 Sensor Node Installer  v2.0
# Target : Raspberry Pi 3, Raspberry Pi OS (Bookworm/Bullseye)
# User   : pi
#
# FIXES applied:
#   - Burns a stable UUID into /etc/machine-id if not already set
#     (prevents identity change on board swap).
#   - Configures chrony NTP client pointed at gateway.local.
#   - Adds pi user to dialout group for /dev/ttyUSB0 access
#     (avoids needing reboot prompt previously).
#   - Writes OTA config values into .env.
#   - Installs systemd watchdog service.
# ============================================================

set -e

REPO_DIR="/home/pi/SoilMonitoringIoT"
VENV_PATH="$REPO_DIR/venv"
SERVICE_NAME="pi3-sensor"
LOG_DIR="/var/log/bpagro"
VERSION_FILE="/etc/bpagro_version"

echo "=============================================="
echo "  BP Agro — Pi 3 Sensor Node Setup  v2.0"
echo "=============================================="

# ── 1. System packages ──────────────────────────────────────
echo "[1/8] Installing system packages..."
sudo apt-get update -q
sudo apt-get install -y \
    python3-pip python3-venv \
    libmariadb-dev-compat mariadb-client \
    git curl chrony \
    python3-rpi.gpio 2>/dev/null || true   # GPIO — optional on non-Pi

# ── 2. Serial port permissions ──────────────────────────────
echo "[2/8] Adding pi to dialout group (serial port access)..."
sudo usermod -aG dialout pi
# Apply immediately without reboot using newgrp inside the script
# The service runs as pi so this takes effect on next login/reboot.

# ── 3. Stable machine identity ──────────────────────────────
echo "[3/8] Ensuring stable machine identity..."
CURRENT_ID=$(cat /etc/machine-id 2>/dev/null || true)
if [ -z "$CURRENT_ID" ] || [ "$CURRENT_ID" = "0000000000000000" ]; then
    NEW_ID=$(python3 -c "import uuid; print(uuid.uuid4().hex)")
    echo "$NEW_ID" | sudo tee /etc/machine-id > /dev/null
    echo "  → Burned new machine-id: $NEW_ID"
else
    echo "  → machine-id already set: $CURRENT_ID"
fi

# ── 4. NTP via gateway ──────────────────────────────────────
echo "[4/8] Configuring NTP (gateway.local as server)..."
sudo tee /etc/chrony/sources.d/gateway.sources > /dev/null << 'NTP'
# BP Agro: use gateway as primary NTP (works without internet)
server gateway.local iburst prefer
# Fallback to public pools if internet is available
pool 2.debian.pool.ntp.org iburst
NTP
sudo systemctl enable --now chrony
sudo chronyc makestep 1.0 3 2>/dev/null || true
echo "  → chrony configured"

# ── 5. Virtual environment ──────────────────────────────────
echo "[5/8] Creating Python virtual environment..."
[ ! -d "$VENV_PATH" ] && python3 -m venv "$VENV_PATH"
"$VENV_PATH/bin/pip" install --upgrade pip -q
"$VENV_PATH/bin/pip" install -r "$REPO_DIR/requirements.txt" -q

# ── 6. Environment file ─────────────────────────────────────
echo "[6/8] Writing .env..."
ENV_FILE="$REPO_DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
    # Prompt for gateway IP if not set
    read -rp "  Gateway IP [192.168.1.100]: " GW_IP
    GW_IP="${GW_IP:-192.168.1.100}"

    read -rp "  OTA version URL (leave blank to disable): " OTA_URL
    read -rp "  OTA HMAC secret (leave blank to disable): " OTA_SECRET

    cat > "$ENV_FILE" << ENV
# BP Agro Pi 3 — auto-generated by setup.sh
GATEWAY_IP=$GW_IP
GATEWAY_API=http://${GW_IP}:5001
DB_HOST=$GW_IP
DB_PORT=3306
DB_USER=DevOps
DB_PASSWORD=DevTeam
DB_NAME=soilmonitornig
MEASUREMENT_INTERVAL=300
SERIAL_PORT=/dev/ttyUSB0
MAX_OFFLINE_RECORDS=1000
OTA_ENABLED=true
OTA_VERSION_URL=${OTA_URL}
OTA_PACKAGE_URL=
OTA_HMAC_SECRET=${OTA_SECRET}
OTA_CHECK_INTERVAL=3600
CALIBRATION_FILE=config/calibration.json
ENV
    echo "  → .env created"
else
    echo "  → .env already exists, skipping"
fi

# ── 7. Log dir + version file ───────────────────────────────
echo "[7/8] Log directory and version stamp..."
sudo mkdir -p "$LOG_DIR"
sudo chown pi:pi "$LOG_DIR"
[ ! -f "$VERSION_FILE" ] && echo "1.0.0" | sudo tee "$VERSION_FILE" > /dev/null

# ── 8. Systemd service ──────────────────────────────────────
echo "[8/8] Installing systemd service (with watchdog)..."
sudo cp "$REPO_DIR/services/services/$SERVICE_NAME.service" /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable "$SERVICE_NAME.service"
sudo systemctl restart "$SERVICE_NAME.service"

sleep 2
STATUS=$(systemctl is-active "$SERVICE_NAME.service")
if [ "$STATUS" = "active" ]; then
    echo "  ✅  $SERVICE_NAME — running"
else
    echo "  ⚠️  $SERVICE_NAME — $STATUS"
    echo "  Check logs: journalctl -u $SERVICE_NAME -n 30"
fi

echo ""
echo "=============================================="
echo "  Setup complete."
echo "  Logs    : journalctl -u $SERVICE_NAME -f"
echo "  Identity: $(cat /etc/machine-id)"
echo "  NTP     : chronyc sources"
echo "  OTA     : $(grep OTA_VERSION_URL $ENV_FILE)"
echo "=============================================="
